### PR TITLE
+ Add a C library header (MCP4728.h).

### PR DESCRIPTION
**Pull request by jofemodo**
+ Add a Makefile.
+ Add a python test for the zynthian's zynaptik module.

### CODE REVIEW

**Comment by jofemodo** [comment]
BTW, it works like a charm! Thanks a lot!

**Comment by marko-pi** [comment]
Hello, I am new to github and I don't quite understand what is going on.

I assume you proposed some changes, like adding C header and transfer some of the code there.  Now I can decide if this changes will be applied to my library, right?

By the way, I am not an expert in C, but I know it is common to use headers in C, so your changes make sense.  Therefore I am inclined to include them.  So I should simply choose "Merge pull request"?

**Comment by jofemodo** [comment]
Hi @marko-pi !

Yes, I've added a header and a Makefile, that is the minimum standard  for distributing a C library in the Free Software world. I also included a little python test for the Zynaptik module, used by zynthian, that includes the MCP4728 for analog output. It's a very simple circuit that uses the default I2C address 0x60 for the MCP4728. We don't need the set_address functionality.

If you agree with the changes, simply "Merge the Pull Request" and the changes will be applied to your repository. This is the typical workflow when managing contributions with github.

Thanks for your excelent work!

**Comment by marko-pi** [comment]
Hello, I am very glad you found my library useful!

Also thank you for making the library more C conventional.

There are still two things I would like to consult about with you.  Most "Tiny GPIO" variables make no sense outside of the code, so I would pull them back into the C code.

On the other hand, "GPIO modes" and "values for pull-ups/downs off, pull-down && pull-up" make sense only if Tiny GPIO functions are called.  This could be useful for someone, so I would leave those in header and expose Tiny GPIO functions too.  Does this thinking make sense to you?

**Comment by jofemodo** [comment]
Hi @marko-pi !

Thanks for merging my little changes. I will integrate your library on zynthian very soon and i always prefer to use the original repos, as it simplify the maintaining.

Regarding your question, yes, it has a lot of sense. You could move to the C file almost all "defines" from the H file, as they are not needed for accessing the exposed API. In such a way the header would be more minimal and simple.

**Comment by marko-pi** [comment]
Well thanks for improving the library!

I have repositioned variables and exposed Tiny GPIO functions - a user might wish to do other GPIO communication apart from MCP4728, so why not use this if it is already available.

**Comment by jofemodo** [comment]
I just tested your changes and it works.

We are currently using the WiringPi library for other GPIO communication on zynthian, but it's currently unmaintained, so the Tiny GPIO could be a good starting point for building a replacement if needed. 

Thanks!

**Pull request merged**
